"""
Country resolution.

Every source in this atlas names countries differently: TRACES prints English
names ("Türkiye", "United Kingdom (Northern Ireland)", "Myanmar/Burma"), CIFER
prints them in Chinese, FSIS prints nothing because it is one country. The rest
of the pipeline needs one ISO 3166-1 alpha-3 code per record, because dedup
blocks on it and the geocoder filters on it.

The rule that used to stand in for this module was `name.upper()[:3]`. It put
the United Kingdom, the United States and the United Arab Emirates in one
bucket called UNI, Spain in one called SPA, and turned every geocoder query
into a string ending in a three-letter fragment no gazetteer recognises. The
table below exists so that never happens again: a name either resolves to a
real code or it resolves to nothing and is reported.
"""

from __future__ import annotations

import re
import unicodedata


ISO3166 = [
    ('ABW', 'AW', 'Aruba'),
    ('AFG', 'AF', 'Afghanistan'),
    ('AGO', 'AO', 'Angola'),
    ('AIA', 'AI', 'Anguilla'),
    ('ALA', 'AX', 'Åland Islands'),
    ('ALB', 'AL', 'Albania'),
    ('AND', 'AD', 'Andorra'),
    ('ARE', 'AE', 'United Arab Emirates'),
    ('ARG', 'AR', 'Argentina'),
    ('ARM', 'AM', 'Armenia'),
    ('ASM', 'AS', 'American Samoa'),
    ('ATA', 'AQ', 'Antarctica'),
    ('ATF', 'TF', 'French Southern Territories'),
    ('ATG', 'AG', 'Antigua and Barbuda'),
    ('AUS', 'AU', 'Australia'),
    ('AUT', 'AT', 'Austria'),
    ('AZE', 'AZ', 'Azerbaijan'),
    ('BDI', 'BI', 'Burundi'),
    ('BEL', 'BE', 'Belgium'),
    ('BEN', 'BJ', 'Benin'),
    ('BES', 'BQ', 'Bonaire, Sint Eustatius and Saba'),
    ('BFA', 'BF', 'Burkina Faso'),
    ('BGD', 'BD', 'Bangladesh'),
    ('BGR', 'BG', 'Bulgaria'),
    ('BHR', 'BH', 'Bahrain'),
    ('BHS', 'BS', 'Bahamas'),
    ('BIH', 'BA', 'Bosnia and Herzegovina'),
    ('BLM', 'BL', 'Saint Barthélemy'),
    ('BLR', 'BY', 'Belarus'),
    ('BLZ', 'BZ', 'Belize'),
    ('BMU', 'BM', 'Bermuda'),
    ('BOL', 'BO', 'Bolivia'),
    ('BRA', 'BR', 'Brazil'),
    ('BRB', 'BB', 'Barbados'),
    ('BRN', 'BN', 'Brunei Darussalam'),
    ('BTN', 'BT', 'Bhutan'),
    ('BVT', 'BV', 'Bouvet Island'),
    ('BWA', 'BW', 'Botswana'),
    ('CAF', 'CF', 'Central African Republic'),
    ('CAN', 'CA', 'Canada'),
    ('CCK', 'CC', 'Cocos (Keeling) Islands'),
    ('CHE', 'CH', 'Switzerland'),
    ('CHL', 'CL', 'Chile'),
    ('CHN', 'CN', 'China'),
    ('CIV', 'CI', "Côte d'Ivoire"),
    ('CMR', 'CM', 'Cameroon'),
    ('COD', 'CD', 'Congo, The Democratic Republic of the'),
    ('COG', 'CG', 'Congo'),
    ('COK', 'CK', 'Cook Islands'),
    ('COL', 'CO', 'Colombia'),
    ('COM', 'KM', 'Comoros'),
    ('CPV', 'CV', 'Cabo Verde'),
    ('CRI', 'CR', 'Costa Rica'),
    ('CUB', 'CU', 'Cuba'),
    ('CUW', 'CW', 'Curaçao'),
    ('CXR', 'CX', 'Christmas Island'),
    ('CYM', 'KY', 'Cayman Islands'),
    ('CYP', 'CY', 'Cyprus'),
    ('CZE', 'CZ', 'Czechia'),
    ('DEU', 'DE', 'Germany'),
    ('DJI', 'DJ', 'Djibouti'),
    ('DMA', 'DM', 'Dominica'),
    ('DNK', 'DK', 'Denmark'),
    ('DOM', 'DO', 'Dominican Republic'),
    ('DZA', 'DZ', 'Algeria'),
    ('ECU', 'EC', 'Ecuador'),
    ('EGY', 'EG', 'Egypt'),
    ('ERI', 'ER', 'Eritrea'),
    ('ESH', 'EH', 'Western Sahara'),
    ('ESP', 'ES', 'Spain'),
    ('EST', 'EE', 'Estonia'),
    ('ETH', 'ET', 'Ethiopia'),
    ('FIN', 'FI', 'Finland'),
    ('FJI', 'FJ', 'Fiji'),
    ('FLK', 'FK', 'Falkland Islands (Malvinas)'),
    ('FRA', 'FR', 'France'),
    ('FRO', 'FO', 'Faroe Islands'),
    ('FSM', 'FM', 'Micronesia, Federated States of'),
    ('GAB', 'GA', 'Gabon'),
    ('GBR', 'GB', 'United Kingdom'),
    ('GEO', 'GE', 'Georgia'),
    ('GGY', 'GG', 'Guernsey'),
    ('GHA', 'GH', 'Ghana'),
    ('GIB', 'GI', 'Gibraltar'),
    ('GIN', 'GN', 'Guinea'),
    ('GLP', 'GP', 'Guadeloupe'),
    ('GMB', 'GM', 'Gambia'),
    ('GNB', 'GW', 'Guinea-Bissau'),
    ('GNQ', 'GQ', 'Equatorial Guinea'),
    ('GRC', 'GR', 'Greece'),
    ('GRD', 'GD', 'Grenada'),
    ('GRL', 'GL', 'Greenland'),
    ('GTM', 'GT', 'Guatemala'),
    ('GUF', 'GF', 'French Guiana'),
    ('GUM', 'GU', 'Guam'),
    ('GUY', 'GY', 'Guyana'),
    ('HKG', 'HK', 'Hong Kong'),
    ('HMD', 'HM', 'Heard Island and McDonald Islands'),
    ('HND', 'HN', 'Honduras'),
    ('HRV', 'HR', 'Croatia'),
    ('HTI', 'HT', 'Haiti'),
    ('HUN', 'HU', 'Hungary'),
    ('IDN', 'ID', 'Indonesia'),
    ('IMN', 'IM', 'Isle of Man'),
    ('IND', 'IN', 'India'),
    ('IOT', 'IO', 'British Indian Ocean Territory'),
    ('IRL', 'IE', 'Ireland'),
    ('IRN', 'IR', 'Iran'),
    ('IRQ', 'IQ', 'Iraq'),
    ('ISL', 'IS', 'Iceland'),
    ('ISR', 'IL', 'Israel'),
    ('ITA', 'IT', 'Italy'),
    ('JAM', 'JM', 'Jamaica'),
    ('JEY', 'JE', 'Jersey'),
    ('JOR', 'JO', 'Jordan'),
    ('JPN', 'JP', 'Japan'),
    ('KAZ', 'KZ', 'Kazakhstan'),
    ('KEN', 'KE', 'Kenya'),
    ('KGZ', 'KG', 'Kyrgyzstan'),
    ('KHM', 'KH', 'Cambodia'),
    ('KIR', 'KI', 'Kiribati'),
    ('KNA', 'KN', 'Saint Kitts and Nevis'),
    ('KOR', 'KR', 'South Korea'),
    ('KWT', 'KW', 'Kuwait'),
    ('LAO', 'LA', 'Laos'),
    ('LBN', 'LB', 'Lebanon'),
    ('LBR', 'LR', 'Liberia'),
    ('LBY', 'LY', 'Libya'),
    ('LCA', 'LC', 'Saint Lucia'),
    ('LIE', 'LI', 'Liechtenstein'),
    ('LKA', 'LK', 'Sri Lanka'),
    ('LSO', 'LS', 'Lesotho'),
    ('LTU', 'LT', 'Lithuania'),
    ('LUX', 'LU', 'Luxembourg'),
    ('LVA', 'LV', 'Latvia'),
    ('MAC', 'MO', 'Macao'),
    ('MAF', 'MF', 'Saint Martin (French part)'),
    ('MAR', 'MA', 'Morocco'),
    ('MCO', 'MC', 'Monaco'),
    ('MDA', 'MD', 'Moldova'),
    ('MDG', 'MG', 'Madagascar'),
    ('MDV', 'MV', 'Maldives'),
    ('MEX', 'MX', 'Mexico'),
    ('MHL', 'MH', 'Marshall Islands'),
    ('MKD', 'MK', 'North Macedonia'),
    ('MLI', 'ML', 'Mali'),
    ('MLT', 'MT', 'Malta'),
    ('MMR', 'MM', 'Myanmar'),
    ('MNE', 'ME', 'Montenegro'),
    ('MNG', 'MN', 'Mongolia'),
    ('MNP', 'MP', 'Northern Mariana Islands'),
    ('MOZ', 'MZ', 'Mozambique'),
    ('MRT', 'MR', 'Mauritania'),
    ('MSR', 'MS', 'Montserrat'),
    ('MTQ', 'MQ', 'Martinique'),
    ('MUS', 'MU', 'Mauritius'),
    ('MWI', 'MW', 'Malawi'),
    ('MYS', 'MY', 'Malaysia'),
    ('MYT', 'YT', 'Mayotte'),
    ('NAM', 'NA', 'Namibia'),
    ('NCL', 'NC', 'New Caledonia'),
    ('NER', 'NE', 'Niger'),
    ('NFK', 'NF', 'Norfolk Island'),
    ('NGA', 'NG', 'Nigeria'),
    ('NIC', 'NI', 'Nicaragua'),
    ('NIU', 'NU', 'Niue'),
    ('NLD', 'NL', 'Netherlands'),
    ('NOR', 'NO', 'Norway'),
    ('NPL', 'NP', 'Nepal'),
    ('NRU', 'NR', 'Nauru'),
    ('NZL', 'NZ', 'New Zealand'),
    ('OMN', 'OM', 'Oman'),
    ('PAK', 'PK', 'Pakistan'),
    ('PAN', 'PA', 'Panama'),
    ('PCN', 'PN', 'Pitcairn'),
    ('PER', 'PE', 'Peru'),
    ('PHL', 'PH', 'Philippines'),
    ('PLW', 'PW', 'Palau'),
    ('PNG', 'PG', 'Papua New Guinea'),
    ('POL', 'PL', 'Poland'),
    ('PRI', 'PR', 'Puerto Rico'),
    ('PRK', 'KP', 'North Korea'),
    ('PRT', 'PT', 'Portugal'),
    ('PRY', 'PY', 'Paraguay'),
    ('PSE', 'PS', 'Palestine, State of'),
    ('PYF', 'PF', 'French Polynesia'),
    ('QAT', 'QA', 'Qatar'),
    ('REU', 'RE', 'Réunion'),
    ('ROU', 'RO', 'Romania'),
    ('RUS', 'RU', 'Russian Federation'),
    ('RWA', 'RW', 'Rwanda'),
    ('SAU', 'SA', 'Saudi Arabia'),
    ('SDN', 'SD', 'Sudan'),
    ('SEN', 'SN', 'Senegal'),
    ('SGP', 'SG', 'Singapore'),
    ('SGS', 'GS', 'South Georgia and the South Sandwich Islands'),
    ('SHN', 'SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('SJM', 'SJ', 'Svalbard and Jan Mayen'),
    ('SLB', 'SB', 'Solomon Islands'),
    ('SLE', 'SL', 'Sierra Leone'),
    ('SLV', 'SV', 'El Salvador'),
    ('SMR', 'SM', 'San Marino'),
    ('SOM', 'SO', 'Somalia'),
    ('SPM', 'PM', 'Saint Pierre and Miquelon'),
    ('SRB', 'RS', 'Serbia'),
    ('SSD', 'SS', 'South Sudan'),
    ('STP', 'ST', 'Sao Tome and Principe'),
    ('SUR', 'SR', 'Suriname'),
    ('SVK', 'SK', 'Slovakia'),
    ('SVN', 'SI', 'Slovenia'),
    ('SWE', 'SE', 'Sweden'),
    ('SWZ', 'SZ', 'Eswatini'),
    ('SXM', 'SX', 'Sint Maarten (Dutch part)'),
    ('SYC', 'SC', 'Seychelles'),
    ('SYR', 'SY', 'Syria'),
    ('TCA', 'TC', 'Turks and Caicos Islands'),
    ('TCD', 'TD', 'Chad'),
    ('TGO', 'TG', 'Togo'),
    ('THA', 'TH', 'Thailand'),
    ('TJK', 'TJ', 'Tajikistan'),
    ('TKL', 'TK', 'Tokelau'),
    ('TKM', 'TM', 'Turkmenistan'),
    ('TLS', 'TL', 'Timor-Leste'),
    ('TON', 'TO', 'Tonga'),
    ('TTO', 'TT', 'Trinidad and Tobago'),
    ('TUN', 'TN', 'Tunisia'),
    ('TUR', 'TR', 'Türkiye'),
    ('TUV', 'TV', 'Tuvalu'),
    ('TWN', 'TW', 'Taiwan'),
    ('TZA', 'TZ', 'Tanzania'),
    ('UGA', 'UG', 'Uganda'),
    ('UKR', 'UA', 'Ukraine'),
    ('UMI', 'UM', 'United States Minor Outlying Islands'),
    ('URY', 'UY', 'Uruguay'),
    ('USA', 'US', 'United States'),
    ('UZB', 'UZ', 'Uzbekistan'),
    ('VAT', 'VA', 'Holy See (Vatican City State)'),
    ('VCT', 'VC', 'Saint Vincent and the Grenadines'),
    ('VEN', 'VE', 'Venezuela'),
    ('VGB', 'VG', 'Virgin Islands, British'),
    ('VIR', 'VI', 'Virgin Islands, U.S.'),
    ('VNM', 'VN', 'Vietnam'),
    ('VUT', 'VU', 'Vanuatu'),
    ('WLF', 'WF', 'Wallis and Futuna'),
    ('WSM', 'WS', 'Samoa'),
    ('YEM', 'YE', 'Yemen'),
    ('ZAF', 'ZA', 'South Africa'),
    ('ZMB', 'ZM', 'Zambia'),
    ('ZWE', 'ZW', 'Zimbabwe'),
]

_NAME_TO_ISO3 = {
    'afghanistan': 'AFG',
    'aland islands': 'ALA',
    'albania': 'ALB',
    'algeria': 'DZA',
    'american samoa': 'ASM',
    'andorra': 'AND',
    'angola': 'AGO',
    'anguilla': 'AIA',
    'antarctica': 'ATA',
    'antigua and barbuda': 'ATG',
    'arab republic of egypt': 'EGY',
    'argentina': 'ARG',
    'argentine republic': 'ARG',
    'armenia': 'ARM',
    'aruba': 'ABW',
    'australia': 'AUS',
    'austria': 'AUT',
    'azerbaijan': 'AZE',
    'bahamas': 'BHS',
    'bahrain': 'BHR',
    'bangladesh': 'BGD',
    'barbados': 'BRB',
    'belarus': 'BLR',
    'belgium': 'BEL',
    'belize': 'BLZ',
    'benin': 'BEN',
    'bermuda': 'BMU',
    'bhutan': 'BTN',
    'bolivarian republic of venezuela': 'VEN',
    'bolivia': 'BOL',
    'bolivia plurinational state of': 'BOL',
    'bonaire': 'BES',
    'bonaire sint eustatius and saba': 'BES',
    'bosnia and herzegovina': 'BIH',
    'botswana': 'BWA',
    'bouvet island': 'BVT',
    'brazil': 'BRA',
    'british indian ocean territory': 'IOT',
    'british virgin islands': 'VGB',
    'brunei': 'BRN',
    'brunei darussalam': 'BRN',
    'bulgaria': 'BGR',
    'burkina faso': 'BFA',
    'burma': 'MMR',
    'burundi': 'BDI',
    'cabo verde': 'CPV',
    'cambodia': 'KHM',
    'cameroon': 'CMR',
    'canada': 'CAN',
    'cape verde': 'CPV',
    'cayman islands': 'CYM',
    'central african republic': 'CAF',
    'chad': 'TCD',
    'chile': 'CHL',
    'china': 'CHN',
    'chinese taipei': 'TWN',
    'christmas island': 'CXR',
    'cocos islands': 'CCK',
    'colombia': 'COL',
    'commonwealth of dominica': 'DMA',
    'commonwealth of the bahamas': 'BHS',
    'commonwealth of the northern mariana islands': 'MNP',
    'comoros': 'COM',
    'congo': 'COD',
    'congo brazzaville': 'COG',
    'congo kinshasa': 'COD',
    'congo the democratic republic of the': 'COD',
    'cook islands': 'COK',
    'costa rica': 'CRI',
    'cote d ivoire': 'CIV',
    'croatia': 'HRV',
    'cuba': 'CUB',
    'curacao': 'CUW',
    'cyprus': 'CYP',
    'czech republic': 'CZE',
    'czechia': 'CZE',
    'democratic people s republic of korea': 'PRK',
    'democratic republic of sao tome and principe': 'STP',
    'democratic republic of the congo': 'COD',
    'democratic republic of timor leste': 'TLS',
    'democratic socialist republic of sri lanka': 'LKA',
    'denmark': 'DNK',
    'djibouti': 'DJI',
    'dominica': 'DMA',
    'dominican republic': 'DOM',
    'drc': 'COD',
    'east timor': 'TLS',
    'eastern republic of uruguay': 'URY',
    'ecuador': 'ECU',
    'egypt': 'EGY',
    'el salvador': 'SLV',
    'england': 'GBR',
    'equatorial guinea': 'GNQ',
    'eritrea': 'ERI',
    'estonia': 'EST',
    'eswatini': 'SWZ',
    'ethiopia': 'ETH',
    'falkland islands': 'FLK',
    'faroe islands': 'FRO',
    'faroes': 'FRO',
    'federal democratic republic of ethiopia': 'ETH',
    'federal democratic republic of nepal': 'NPL',
    'federal republic of germany': 'DEU',
    'federal republic of nigeria': 'NGA',
    'federal republic of somalia': 'SOM',
    'federated states of micronesia': 'FSM',
    'federative republic of brazil': 'BRA',
    'fiji': 'FJI',
    'finland': 'FIN',
    'france': 'FRA',
    'french guiana': 'GUF',
    'french polynesia': 'PYF',
    'french republic': 'FRA',
    'french southern territories': 'ATF',
    'gabon': 'GAB',
    'gabonese republic': 'GAB',
    'gambia': 'GMB',
    'georgia': 'GEO',
    'germany': 'DEU',
    'ghana': 'GHA',
    'gibraltar': 'GIB',
    'grand duchy of luxembourg': 'LUX',
    'great britain': 'GBR',
    'greece': 'GRC',
    'greenland': 'GRL',
    'grenada': 'GRD',
    'guadeloupe': 'GLP',
    'guam': 'GUM',
    'guatemala': 'GTM',
    'guernsey': 'GGY',
    'guinea': 'GIN',
    'guinea bissau': 'GNB',
    'guyana': 'GUY',
    'haiti': 'HTI',
    'hashemite kingdom of jordan': 'JOR',
    'heard island and mcdonald islands': 'HMD',
    'hellenic republic': 'GRC',
    'holland': 'NLD',
    'holy see': 'VAT',
    'honduras': 'HND',
    'hong kong': 'HKG',
    'hong kong special administrative region of china': 'HKG',
    'hungary': 'HUN',
    'iceland': 'ISL',
    'independent state of papua new guinea': 'PNG',
    'independent state of samoa': 'WSM',
    'india': 'IND',
    'indonesia': 'IDN',
    'iran': 'IRN',
    'iran islamic republic of': 'IRN',
    'iraq': 'IRQ',
    'ireland': 'IRL',
    'islamic republic of afghanistan': 'AFG',
    'islamic republic of iran': 'IRN',
    'islamic republic of mauritania': 'MRT',
    'islamic republic of pakistan': 'PAK',
    'isle of man': 'IMN',
    'israel': 'ISR',
    'italian republic': 'ITA',
    'italy': 'ITA',
    'ivory coast': 'CIV',
    'jamaica': 'JAM',
    'japan': 'JPN',
    'jersey': 'JEY',
    'jordan': 'JOR',
    'kazakhstan': 'KAZ',
    'kenya': 'KEN',
    'kingdom of bahrain': 'BHR',
    'kingdom of belgium': 'BEL',
    'kingdom of bhutan': 'BTN',
    'kingdom of cambodia': 'KHM',
    'kingdom of denmark': 'DNK',
    'kingdom of eswatini': 'SWZ',
    'kingdom of lesotho': 'LSO',
    'kingdom of morocco': 'MAR',
    'kingdom of norway': 'NOR',
    'kingdom of saudi arabia': 'SAU',
    'kingdom of spain': 'ESP',
    'kingdom of sweden': 'SWE',
    'kingdom of thailand': 'THA',
    'kingdom of the netherlands': 'NLD',
    'kingdom of tonga': 'TON',
    'kiribati': 'KIR',
    'korea': 'KOR',
    'korea democratic people s republic of': 'PRK',
    'korea north': 'PRK',
    'korea republic of': 'KOR',
    'korea south': 'KOR',
    'kosovo': 'XKX',
    'kuwait': 'KWT',
    'kyrgyz republic': 'KGZ',
    'kyrgyzstan': 'KGZ',
    'lao people s democratic republic': 'LAO',
    'laos': 'LAO',
    'latvia': 'LVA',
    'lebanese republic': 'LBN',
    'lebanon': 'LBN',
    'lesotho': 'LSO',
    'liberia': 'LBR',
    'libya': 'LBY',
    'liechtenstein': 'LIE',
    'lithuania': 'LTU',
    'luxembourg': 'LUX',
    'macao': 'MAC',
    'macao special administrative region of china': 'MAC',
    'macau': 'MAC',
    'macedonia': 'MKD',
    'madagascar': 'MDG',
    'malawi': 'MWI',
    'malaysia': 'MYS',
    'maldives': 'MDV',
    'mali': 'MLI',
    'malta': 'MLT',
    'malvinas': 'FLK',
    'marshall islands': 'MHL',
    'martinique': 'MTQ',
    'mauritania': 'MRT',
    'mauritius': 'MUS',
    'mayotte': 'MYT',
    'mexico': 'MEX',
    'micronesia': 'FSM',
    'micronesia federated states of': 'FSM',
    'moldova': 'MDA',
    'moldova republic of': 'MDA',
    'monaco': 'MCO',
    'mongolia': 'MNG',
    'montenegro': 'MNE',
    'montserrat': 'MSR',
    'morocco': 'MAR',
    'mozambique': 'MOZ',
    'myanmar': 'MMR',
    'myanmar burma': 'MMR',
    'namibia': 'NAM',
    'nauru': 'NRU',
    'nepal': 'NPL',
    'netherlands': 'NLD',
    'new caledonia': 'NCL',
    'new zealand': 'NZL',
    'nicaragua': 'NIC',
    'niger': 'NER',
    'nigeria': 'NGA',
    'niue': 'NIU',
    'norfolk island': 'NFK',
    'north korea': 'PRK',
    'north macedonia': 'MKD',
    'northern ireland': 'GBR',
    'northern mariana islands': 'MNP',
    'norway': 'NOR',
    'oman': 'OMN',
    'pakistan': 'PAK',
    'palau': 'PLW',
    'palestine': 'PSE',
    'palestine state of': 'PSE',
    'panama': 'PAN',
    'papua new guinea': 'PNG',
    'paraguay': 'PRY',
    'people s democratic republic of algeria': 'DZA',
    'people s republic of bangladesh': 'BGD',
    'people s republic of china': 'CHN',
    'peru': 'PER',
    'philippines': 'PHL',
    'pitcairn': 'PCN',
    'plurinational state of bolivia': 'BOL',
    'poland': 'POL',
    'portugal': 'PRT',
    'portuguese republic': 'PRT',
    'principality of andorra': 'AND',
    'principality of liechtenstein': 'LIE',
    'principality of monaco': 'MCO',
    'puerto rico': 'PRI',
    'qatar': 'QAT',
    'republic of albania': 'ALB',
    'republic of angola': 'AGO',
    'republic of armenia': 'ARM',
    'republic of austria': 'AUT',
    'republic of azerbaijan': 'AZE',
    'republic of belarus': 'BLR',
    'republic of benin': 'BEN',
    'republic of bosnia and herzegovina': 'BIH',
    'republic of botswana': 'BWA',
    'republic of bulgaria': 'BGR',
    'republic of burundi': 'BDI',
    'republic of cabo verde': 'CPV',
    'republic of cameroon': 'CMR',
    'republic of chad': 'TCD',
    'republic of chile': 'CHL',
    'republic of colombia': 'COL',
    'republic of costa rica': 'CRI',
    'republic of cote d ivoire': 'CIV',
    'republic of croatia': 'HRV',
    'republic of cuba': 'CUB',
    'republic of cyprus': 'CYP',
    'republic of djibouti': 'DJI',
    'republic of ecuador': 'ECU',
    'republic of el salvador': 'SLV',
    'republic of equatorial guinea': 'GNQ',
    'republic of estonia': 'EST',
    'republic of fiji': 'FJI',
    'republic of finland': 'FIN',
    'republic of ghana': 'GHA',
    'republic of guatemala': 'GTM',
    'republic of guinea': 'GIN',
    'republic of guinea bissau': 'GNB',
    'republic of guyana': 'GUY',
    'republic of haiti': 'HTI',
    'republic of honduras': 'HND',
    'republic of iceland': 'ISL',
    'republic of india': 'IND',
    'republic of indonesia': 'IDN',
    'republic of iraq': 'IRQ',
    'republic of kazakhstan': 'KAZ',
    'republic of kenya': 'KEN',
    'republic of kiribati': 'KIR',
    'republic of korea': 'KOR',
    'republic of latvia': 'LVA',
    'republic of liberia': 'LBR',
    'republic of lithuania': 'LTU',
    'republic of madagascar': 'MDG',
    'republic of malawi': 'MWI',
    'republic of maldives': 'MDV',
    'republic of mali': 'MLI',
    'republic of malta': 'MLT',
    'republic of mauritius': 'MUS',
    'republic of moldova': 'MDA',
    'republic of mozambique': 'MOZ',
    'republic of myanmar': 'MMR',
    'republic of namibia': 'NAM',
    'republic of nauru': 'NRU',
    'republic of nicaragua': 'NIC',
    'republic of north macedonia': 'MKD',
    'republic of palau': 'PLW',
    'republic of panama': 'PAN',
    'republic of paraguay': 'PRY',
    'republic of peru': 'PER',
    'republic of poland': 'POL',
    'republic of san marino': 'SMR',
    'republic of senegal': 'SEN',
    'republic of serbia': 'SRB',
    'republic of seychelles': 'SYC',
    'republic of sierra leone': 'SLE',
    'republic of singapore': 'SGP',
    'republic of slovenia': 'SVN',
    'republic of south africa': 'ZAF',
    'republic of south sudan': 'SSD',
    'republic of suriname': 'SUR',
    'republic of tajikistan': 'TJK',
    'republic of the congo': 'COG',
    'republic of the gambia': 'GMB',
    'republic of the marshall islands': 'MHL',
    'republic of the niger': 'NER',
    'republic of the philippines': 'PHL',
    'republic of the sudan': 'SDN',
    'republic of trinidad and tobago': 'TTO',
    'republic of tunisia': 'TUN',
    'republic of turkiye': 'TUR',
    'republic of uganda': 'UGA',
    'republic of uzbekistan': 'UZB',
    'republic of vanuatu': 'VUT',
    'republic of yemen': 'YEM',
    'republic of zambia': 'ZMB',
    'republic of zimbabwe': 'ZWE',
    'reunion': 'REU',
    'romania': 'ROU',
    'russia': 'RUS',
    'russian federation': 'RUS',
    'rwanda': 'RWA',
    'rwandese republic': 'RWA',
    'saint barthelemy': 'BLM',
    'saint helena': 'SHN',
    'saint helena ascension and tristan da cunha': 'SHN',
    'saint kitts and nevis': 'KNA',
    'saint lucia': 'LCA',
    'saint martin': 'MAF',
    'saint pierre and miquelon': 'SPM',
    'saint vincent and the grenadines': 'VCT',
    'samoa': 'WSM',
    'san marino': 'SMR',
    'sao tome and principe': 'STP',
    'saudi arabia': 'SAU',
    'scotland': 'GBR',
    'senegal': 'SEN',
    'serbia': 'SRB',
    'seychelles': 'SYC',
    'sierra leone': 'SLE',
    'singapore': 'SGP',
    'sint maarten': 'SXM',
    'slovak republic': 'SVK',
    'slovakia': 'SVK',
    'slovenia': 'SVN',
    'socialist republic of viet nam': 'VNM',
    'solomon islands': 'SLB',
    'somalia': 'SOM',
    'south africa': 'ZAF',
    'south georgia and the south sandwich islands': 'SGS',
    'south korea': 'KOR',
    'south sudan': 'SSD',
    'spain': 'ESP',
    'sri lanka': 'LKA',
    'st helena': 'SHN',
    'state of eritrea': 'ERI',
    'state of israel': 'ISR',
    'state of kuwait': 'KWT',
    'state of palestine': 'PSE',
    'state of qatar': 'QAT',
    'sudan': 'SDN',
    'sultanate of oman': 'OMN',
    'suriname': 'SUR',
    'svalbard and jan mayen': 'SJM',
    'swaziland': 'SWZ',
    'sweden': 'SWE',
    'swiss confederation': 'CHE',
    'switzerland': 'CHE',
    'syria': 'SYR',
    'syrian arab republic': 'SYR',
    'taiwan': 'TWN',
    'taiwan province of china': 'TWN',
    'tajikistan': 'TJK',
    'tanzania': 'TZA',
    'tanzania united republic of': 'TZA',
    'thailand': 'THA',
    'timor leste': 'TLS',
    'togo': 'TGO',
    'togolese republic': 'TGO',
    'tokelau': 'TKL',
    'tonga': 'TON',
    'trinidad and tobago': 'TTO',
    'tunisia': 'TUN',
    'turkey': 'TUR',
    'turkiye': 'TUR',
    'turkmenistan': 'TKM',
    'turks and caicos islands': 'TCA',
    'tuvalu': 'TUV',
    'uae': 'ARE',
    'uganda': 'UGA',
    'uk': 'GBR',
    'ukraine': 'UKR',
    'union of the comoros': 'COM',
    'united arab emirates': 'ARE',
    'united kingdom': 'GBR',
    'united kingdom northern ireland': 'GBR',
    'united kingdom of great britain and northern ireland': 'GBR',
    'united mexican states': 'MEX',
    'united republic of tanzania': 'TZA',
    'united states': 'USA',
    'united states minor outlying islands': 'UMI',
    'united states of america': 'USA',
    'uruguay': 'URY',
    'us': 'USA',
    'usa': 'USA',
    'uzbekistan': 'UZB',
    'vanuatu': 'VUT',
    'vatican': 'VAT',
    'venezuela': 'VEN',
    'venezuela bolivarian republic of': 'VEN',
    'viet nam': 'VNM',
    'vietnam': 'VNM',
    'virgin islands': 'VGB',
    'virgin islands british': 'VGB',
    'virgin islands of the united states': 'VIR',
    'virgin islands u s': 'VIR',
    'wales': 'GBR',
    'wallis and futuna': 'WLF',
    'western sahara': 'ESH',
    'yemen': 'YEM',
    'zambia': 'ZMB',
    'zimbabwe': 'ZWE',
}

_ZH_TO_ISO3 = {
    '中国': 'CHN',
    '丹麦': 'DNK',
    '乌克兰': 'UKR',
    '乌拉圭': 'URY',
    '以色列': 'ISR',
    '俄罗斯': 'RUS',
    '保加利亚': 'BGR',
    '克罗地亚': 'HRV',
    '冰岛': 'ISL',
    '加拿大': 'CAN',
    '加纳': 'GHA',
    '匈牙利': 'HUN',
    '南非': 'ZAF',
    '卢森堡': 'LUX',
    '印度': 'IND',
    '印度尼西亚': 'IDN',
    '厄瓜多尔': 'ECU',
    '哥斯达黎加': 'CRI',
    '土耳其': 'TUR',
    '埃及': 'EGY',
    '塞内加尔': 'SEN',
    '塞尔维亚': 'SRB',
    '墨西哥': 'MEX',
    '奥地利': 'AUT',
    '孟加拉国': 'BGD',
    '尼日利亚': 'NGA',
    '巴基斯坦': 'PAK',
    '巴拉圭': 'PRY',
    '巴拿马': 'PAN',
    '巴西': 'BRA',
    '希腊': 'GRC',
    '德国': 'DEU',
    '意大利': 'ITA',
    '拉脱维亚': 'LVA',
    '挪威': 'NOR',
    '捷克': 'CZE',
    '摩洛哥': 'MAR',
    '斯洛伐克': 'SVK',
    '斯洛文尼亚': 'SVN',
    '斯里兰卡': 'LKA',
    '新加坡': 'SGP',
    '新西兰': 'NZL',
    '日本': 'JPN',
    '智利': 'CHL',
    '比利时': 'BEL',
    '法国': 'FRA',
    '波兰': 'POL',
    '泰国': 'THA',
    '澳大利亚': 'AUS',
    '爱尔兰': 'IRL',
    '爱沙尼亚': 'EST',
    '瑞典': 'SWE',
    '瑞士': 'CHE',
    '白俄罗斯': 'BLR',
    '秘鲁': 'PER',
    '突尼斯': 'TUN',
    '立陶宛': 'LTU',
    '纳米比亚': 'NAM',
    '罗马尼亚': 'ROU',
    '美国': 'USA',
    '肯尼亚': 'KEN',
    '芬兰': 'FIN',
    '英国': 'GBR',
    '荷兰': 'NLD',
    '菲律宾': 'PHL',
    '葡萄牙': 'PRT',
    '蒙古': 'MNG',
    '西班牙': 'ESP',
    '越南': 'VNM',
    '阿根廷': 'ARG',
    '韩国': 'KOR',
    '马来西亚': 'MYS',
}


_BY_ISO3 = {a3: (a2, name) for a3, a2, name in ISO3166}
_BY_ISO2 = {a2: a3 for a3, a2, _ in ISO3166}

_unresolved: dict[str, int] = {}


def _norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c)).lower()
    s = re.sub(r"\(.*?\)", " ", s)          # "United Kingdom (Northern Ireland)"
    s = re.sub(r"[^a-z0-9]+", " ", s).strip()
    s = re.sub(r"^the\s+", "", s)
    return s


def to_iso3(value: str | None) -> str | None:
    """ISO 3166-1 alpha-3 for a country name, code, or Chinese name.

    Returns None when the value cannot be resolved, and records it so
    `unresolved()` can report what a source is publishing that this table does
    not know. Nothing is guessed: an unrecognised name produces no code rather
    than a plausible-looking one.
    """
    if not value:
        return None
    raw = str(value).strip()
    if not raw:
        return None

    if raw in _ZH_TO_ISO3:                       # CIFER
        return _ZH_TO_ISO3[raw]

    up = raw.upper()
    if len(up) == 3 and up in _BY_ISO3:
        return up
    if len(up) == 2 and up in _BY_ISO2:
        return _BY_ISO2[up]

    key = _norm(raw)
    hit = _NAME_TO_ISO3.get(key)
    if hit:
        return hit

    # "Spain / España", "Myanmar/Burma", "Congo, Republic of the"
    for part in re.split(r"[/|]| and | e | y ", raw):
        k = _norm(part)
        if k and k in _NAME_TO_ISO3:
            return _NAME_TO_ISO3[k]

    _unresolved[raw] = _unresolved.get(raw, 0) + 1
    return None


def to_iso2(iso3: str | None) -> str | None:
    """Alpha-2, which is what Nominatim's countrycodes filter takes."""
    if not iso3:
        return None
    entry = _BY_ISO3.get(iso3.upper())
    return entry[0] if entry else None


def english_name(iso3: str | None) -> str | None:
    """Plain English name, for the geocoder query and the map legend."""
    if not iso3:
        return None
    entry = _BY_ISO3.get(iso3.upper())
    return entry[1] if entry else None


def unresolved() -> dict[str, int]:
    """Country strings seen this run that the table could not place."""
    return dict(sorted(_unresolved.items(), key=lambda kv: -kv[1]))
